- repo: local
  hooks:
    - id: rustfmt
      name: rustfmt
      entry: cargo fmt --all --check
      language: system
      types: [rust]
- repo: local
  hooks:
    - id: clippy
      name: clippy
      entry: cargo clippy --all-targets --all-features
      language: system
      types: [rust]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: detect-merge-conflict
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
