[package]
name = "budget"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
crossterm = "0.29.0"
csv = "1.3.1"
diesel = { version = "2.2.10", features = ["chrono", "postgres"] }
serde = "1.0.219"
serde_json = "1.0.140"
